# Generated by Django 4.0.8 on 2022-10-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontroluser',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='smartcontroluser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
