# Generated by Django 4.0.8 on 2022-10-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smartcontroluser_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontroluser',
            name='token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
