# Generated by Django 4.0.8 on 2022-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_binmanageruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binmanageruser',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='binmanageruser',
            name='is_firstuse',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='binmanageruser',
            name='is_root',
            field=models.BooleanField(),
        ),
    ]
