version: '3.8'

services:
  web:
    build:
      context: ./multilogin
      dockerfile: Dockerfile
    image: mitdeveloper/multilogin:dev
    command: gunicorn multilogin.wsgi:application --bind 0.0.0.0:4000
    volumes:
      - static_volume:/usr/src/multilogin/static
    expose:
      - 4000
  nginx:
    image: nginx:alpine
    container_name: multilogin-nginx
    restart: unless-stopped
    ports:
      - 4000:80
    volumes:
      - static_volume:/usr/src/multilogin/static
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - web
volumes:
  redisdata:
  static_volume: